### ISSUE TITLE
"Failed to create shortcut. CoInitialize has not been called."

### ISSUE THREAD

**Issue by Nyges** [maichiu/FlashpointShortcutMaker#4]
I put both this and CLIFp into my Flashpoint root and it says this

**Comment by n0samu** [comment]
Hi, this is a bug in CLIFp. I've reported it via the issue linked above.

**Comment by oblivioncth** [comment]
@Nyges Just in case you see this first:

This has been fixed in the release I just put out. Thanks for reporting the bug.
